### ISSUE TITLE
Different from the raw paper

### ISSUE THREAD

**Issue by HaishuoFang** [roomylee/rcnn-text-classification#6]
ur work is very perfect!
But the raw paper use the previous embedding and cell_state as input to calculate current cell_state as context left.your code use normal RNN(current embedding and previous cell_state) to calculate the cell_state.
I try write code as raw paper,but i find it is very slow.
what is your opinion?

**Comment by roomylee** [comment]
@HaishuoFang 
Thanks. Is this [paper](https://www.aaai.org/ocs/index.php/AAAI/AAAI15/paper/view/9745) the raw paper what you said?
In the paper, current embedding and previous left & right cell_state are used to make current cell_state (x_i). To implement it, i use RNN and make the previous cell_state by shifting the result of RNN.

Checking this code could be help u.
https://github.com/roomylee/rcnn-text-classification/blob/f1295073cbbafdbd1b6706b7b5bcecec5fdadb1d/rcnn.py#L34

**Comment by HaishuoFang** [comment]
I got it!thanks
